version: '3'
services:

  dash:
    build:
      context: ./
      dockerfile: dockerfile-dash
    container_name: project_web
    restart: always
    ports:
      - "80:8050"
    environment:
      - TARGET=LIVE
    volumes:
      - ./app:/app
